# Site settings
title: "wido1593"
bye_message: "End of Page"
baseurl: ""
url: "https://wido1593.github.io"
#disqus: gjuniioor

# Header settings
id: "wido1593"
nick: "jaehoonman"

mail:
    domain: "wido1593"
    ext: "g"
source_code:
    server: "github.com"
    nick: "wido1593"
blog:
    nick: "jaehoonman"
    server: "tistory.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
future: true #post 작성 시 미래의 날짜도 개시할 것인지.